---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3445545312-dJDAaohGAUZiR5EF7uIW1qRPtg7dmK4uN52siEN
:access_token_secret: yZSKzCXbW7eiCcsDbsdcAGlmygj5XeRclNlVFhAR8cH5n
